console.log('Pull request for new feature')
console.log('Assigning pull request to specific member')
console.log('Squash and merge pull request')
console.log('Rebase and merge method ')
console.log('Closing pull request')
